version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10-node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      - run: 
          name: Alter path
          command: echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Install dependencies
      - run:
          name: Install Python Dependencies
          command: pip install --user -r requirements.txt

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # Test
      - run:
          name: Tests
          command: yarn test

      # Coverage
      - run:
          name: Coverage
          command: yarn codecov
